// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgDqOm03u2Ee6QNHuZXBL09s5Tdqjoafw',
    appId: '1:327112416902:web:4d8c0b47820328c9c7bb07',
    messagingSenderId: '327112416902',
    projectId: 'bakery-a8469',
    authDomain: 'bakery-a8469.firebaseapp.com',
    storageBucket: 'bakery-a8469.appspot.com',
    measurementId: 'G-CVBZ4QRMGX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4mSz4op_s2zfTTDL8Qa80nAxi6vrdD2s',
    appId: '1:327112416902:android:17b8da7006751c9fc7bb07',
    messagingSenderId: '327112416902',
    projectId: 'bakery-a8469',
    storageBucket: 'bakery-a8469.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8o86xeirOxSKxJaq33KTl59uwPPrO1M4',
    appId: '1:327112416902:ios:a3ea78dc872d0abfc7bb07',
    messagingSenderId: '327112416902',
    projectId: 'bakery-a8469',
    storageBucket: 'bakery-a8469.appspot.com',
    iosClientId: '327112416902-7rlcqf2o9g0dqc3pjd0rdhfcftj15b46.apps.googleusercontent.com',
    iosBundleId: 'com.example.nBaz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8o86xeirOxSKxJaq33KTl59uwPPrO1M4',
    appId: '1:327112416902:ios:a3ea78dc872d0abfc7bb07',
    messagingSenderId: '327112416902',
    projectId: 'bakery-a8469',
    storageBucket: 'bakery-a8469.appspot.com',
    iosClientId: '327112416902-7rlcqf2o9g0dqc3pjd0rdhfcftj15b46.apps.googleusercontent.com',
    iosBundleId: 'com.example.nBaz',
  );
}
